version: 2
jobs:
  instruqt-validate:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Validate
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            echo "Running instruqt track validate..."
            for dir in $(ls -d /root/project/instruqt-tracks/*); do
              cd $dir && instruqt track validate
            done
  instruqt-test-vault-basics:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/vault-basics
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  instruqt-test-vault-dynamic-database-credentials:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/vault-dynamic-database-credentials
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  instruqt-test-vault-dynamic-secrets-aws:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/vault-dynamic-secrets-aws
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  instruqt-test-vault-aws-auth-method:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/vault-aws-auth-method
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  instruqt-test-vault-encryption-as-a-service:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run Instruqt Test
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/vault-encryption-as-a-service
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]
            do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - instruqt-validate:
          filters:
            branches:
              only: main
      - instruqt-test-vault-basics:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: main
      - instruqt-test-vault-dynamic-database-credentials:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: main
      - instruqt-test-vault-dynamic-secrets-aws:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: main
      - instruqt-test-vault-aws-auth-method:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: main
      - instruqt-test-vault-encryption-as-a-service:
          requires:
            - instruqt-validate
          filters:
            branches:
              only: main
  nightly-build:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - instruqt-validate
      - instruqt-test-vault-basics:
          requires:
            - instruqt-validate
      - instruqt-test-vault-dynamic-database-credentials:
          requires:
            - instruqt-validate
      - instruqt-test-vault-dynamic-secrets-aws:
          requires:
            - instruqt-validate
      - instruqt-test-vault-aws-auth-method:
          requires:
            - instruqt-validate
      - instruqt-test-vault-encryption-as-a-service:
          requires:
            - instruqt-validate
